### ISSUE TITLE
Add warning / info for "install from github" dialog

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#518] opened 2020-02-19 17:48 UTC
When a user reports a problem on Facebook, a lot of users recommend to reinstall the adapter by using the GitHub url. In my opinion this is very dangerous and leads to an installation of an undefined state of the adapter (since a branch will be installed instead of a specific version).

My feature request: Hide the "install from GitHub" button when expert mode is not active and show a warning message within the dialog box what will happen and what are the consequences when the feature will be used.

In most cases, the installation from GitHub will lead to more issues instead of solving a problem.

**Comment by Apollon77** [comment] 2020-02-19 23:29
duplicate of https://github.com/ioBroker/ioBroker.admin/issues/285 ;-) but yes really important

**Closed by Apollon77** 2020-02-19 23:29 UTC

**Comment by klein0r** [comment] 2020-02-20 18:40
Sorry 😄Seems I have to create a pull request

**Comment by Apollon77** [comment] 2020-02-20 18:46
Np ;-) and yes .. your‘re welcome ;-)
