### ISSUE TITLE
Admin shows old versions again after toggling menu back and forth

### ISSUE THREAD

**Issue by klausiob** [ioBroker/ioBroker.admin#1385] opened 2022-03-17 19:12 UTC
If I update some Adapters the page shows immedently the new versions.
If I then click on Overview in the left menu and go back to Adapters, it shows the old versions again. 

 - Adapter version: Admin 5.2.3
 - JS-Controller version:  3.3.22
 - Node version: v14.18.1
 - Operating system: linux on Raspi

**Comment by Feuer-sturm** [comment] 2022-03-18 00:54
@klausiob please verify your issue with current stable Version 5.3.1

**Comment by klausiob** [comment] 2022-03-18 16:28
same error

**Comment by klausiob** [comment] 2022-03-18 17:26
Sorry, false button

**Comment by Feuer-sturm** [comment] 2022-03-18 20:11
I have the same issue with admin 5.3.2 as well.
It seems to be a refreshing issue. After refreshing the complete site everything is fine.

**Comment by klausiob** [comment] 2022-03-18 20:52
I thought is the same error as with VIS in the web adapter. Please refer
https://github.com/ioBroker/ioBroker.web/issues/180

**Comment by GermanBluefox** [comment] 2022-04-03 10:06
> I thought is the same error as with VIS in the web adapter. Please refer [ioBroker/ioBroker.web#180](https://github.com/ioBroker/ioBroker.web/issues/180)

These errors have nothing common...

**Comment by Feuer-sturm** [comment] 2022-06-09 20:00
Issue is still there with Admin 6.0.2

**Comment by GermanBluefox** [comment] 2022-06-19 18:58
Fixed in 6.0.6

**Comment by Feuer-sturm** [comment] 2022-06-19 20:21
Tested with Admin 6.0.6 but on my system this issue is not fixed. The problem is still there.

**Comment by GermanBluefox** [comment] 2022-06-20 15:28
PLease retry with 6.0.7

**Comment by Feuer-sturm** [comment] 2022-06-21 05:11
Is fixed in 6.0.7

**Closed by Feuer-sturm** 2022-06-21 05:11 UTC
Labels: bug, fixed
