### ISSUE TITLE
Updating admin through the admin UI does not update the version in the top right corner.

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#212] opened 2018-03-08 19:19 UTC
See screenshot/comment in https://github.com/ioBroker/ioBroker.admin/issues/208#issuecomment-371593125

**Comment by rafale77** [comment] 2018-04-01 09:57
<img width="1882" alt="iobroker" src="https://user-images.githubusercontent.com/15803952/38171962-51574ed2-3558-11e8-97c5-169a165e3a4e.png">

I can confirm I have been having this problem for a while. Is there anything I need to do to migrate from 2.0.9?

**Comment by Apollon77** [comment] 2018-04-01 12:34
Does it update the version number when you clear Browser cache or restart the browser?

**Comment by BuZZy1337** [comment] 2018-04-01 12:40
I updated yesterday to 3.3.5 for testing purposes.. And as the update was done it showed 2.0.9.. Then i closed the browser and went off the computer.. After 30 minutes I came back to the computer and opened the Webinterface again, then it showed 3.3.5.. I guess it has definitely something to do with caching..

**Comment by rafale77** [comment] 2018-04-01 22:14
Well I did not have the JS-controller installed so I could not upgrade the admin adapter from the UI and had to do it through SSH using the an npm install. After installing the JS-Controller and manually reinstalling the admin adapter, it is now updating from the UI and using the iobroker command and the top of the screen shows 3.3.5.

**Comment by BuZZy1337** [comment] 2018-04-04 09:03
Got the same issue now again after updating .. Upload of the admin adapter solved the problem.

**Comment by AlCalzone** [comment] 2018-04-04 09:09
> Upload of the admin adapter solved the problem.

But isn't that already being done automatically on update?

**Comment by Apollon77** [comment] 2018-04-04 09:41
Should be (except when install from GitHub sometimes not ...)

**Comment by BuZZy1337** [comment] 2018-04-04 09:50
I was on admin 2.0.9 did an
`iobroker upgrade self`
Over the command line and that updated the admin.. I restarted the whole system, after opening the Webinterface it showed 2.0.9 in the upper right corner. After doing the admin upload it immediately showed the correct version 3.3.5 in the corner..

**Comment by Homoran** [comment] 2018-04-04 09:53
I can confirm this isuue too.
Only an upload and a forced refresh sets the version info correctly

**Comment by Apollon77** [comment] 2018-04-04 09:57
Which js-controller? <1.3.0? As soon as an "js-controller" upgrade also updates the Admin (because of npm deps) there is no "upload" executed. We may need to add that somewhere in postinstall script or such (@AlCalzone @GermanBluefox what you think?)

**Comment by BuZZy1337** [comment] 2018-04-04 10:02
I was on js-controller 1.2.3..

**Comment by Apollon77** [comment] 2018-04-04 10:05
Then reason for the upgrade of admin is known ... (finally fixed in 1.3.0) ... but problem remains. We should do an upload admin after install of js-controller

**Comment by GermanBluefox** [comment] 2018-04-04 10:48
Fixed on git yesterday

ср, 4 апр. 2018 г., 12:05 Ingo Fischer <notifications@github.com>:

**Closed** 2018-04-12 16:14 UTC
Labels: fixed

**Comment by BuZZy1337** [comment] 2018-04-14 19:29
Yep, looks good.. Did an update again from admin 2.0.9 to 3.3.9.. Correct version was shown immediately after update was done.

**Comment by DutchmanNL** [comment] 2018-04-14 22:36
Confirmed here at 3 different installations
