### ISSUE TITLE
Admin 5.0.10 : Quelle fehlt im LOG

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#777] opened 2021-04-28 11:41 UTC
Quelle fehlt im LOG auf Multihost
![grafik](https://user-images.githubusercontent.com/6681528/116397838-5ea51480-a827-11eb-81d6-2107e1ceea83.png)

**Comment by GermanBluefox** [comment] 2021-05-12 19:02
Cannot reproduce

**Comment by GermanBluefox** [comment] 2021-05-13 07:14
Can someone confirm it?

**Comment by Feuer-sturm** [comment] 2021-05-13 08:24
I can set up an iobroker slave to enable a multihost system and check how it looks like on my system

**Comment by GermanBluefox** [comment] 2021-05-13 16:28
Do you know, that you can setup second js-controller on the same PC/OS? Just install iobroker.js-controller in some other directory and change iobroker-data/iobroker.json => system.hostname on something else (e.g. OtherHostName) and check the settings for states and objects in the same file (redis/file and ports). Then just start js-controller `node node_modules/iobroker.js-controller/main.js --logs`

**Comment by Feuer-sturm** [comment] 2021-05-13 17:36
Until now I didn't know :-)
I am using proxmox and I have a LXC container with a fresh ubuntu. So it is just one line with the iobroker script to install a new ioBroker.

**Comment by Feuer-sturm** [comment] 2021-05-13 18:23
Master: Admin 5.0.22 - js-controller 3.3.9
Slave: Admin 5.0.22 - js-controlelr 3.3.9

I just added a new iobroker and configured a master and a slave using this steps https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/config/multihost.md

If I switch in the menu "Protokoll" to the new slave the coloum "Quelle" is filled.


![grafik](https://user-images.githubusercontent.com/25422320/118168744-79cb7300-b428-11eb-96ca-df0aafffb2d5.png)

@arteck Is the problem still there on your system with current Admin5?

**Comment by arteck** [comment] 2021-05-13 19:32
![grafik](https://user-images.githubusercontent.com/6681528/118177232-ae442c80-b432-11eb-8533-246028145c83.png)
here new log ..admin 5.0.22

**Comment by GermanBluefox** [comment] 2021-05-13 22:45
@Feuer-sturm May be we should install something (or event zwave2) on second host?

**Comment by Feuer-sturm** [comment] 2021-05-13 23:15
I just installed on my slave zwave as well
![grafik](https://user-images.githubusercontent.com/25422320/118197870-19e8c280-b450-11eb-89ae-43bc94155def.png)

And I see the same behavior than @arteck 
![grafik](https://user-images.githubusercontent.com/25422320/118198012-63d1a880-b450-11eb-987c-6f0f312557d9.png)

Then I saw that my slave had a wrong time zone. After setting the correct time zone and restarting the zwave adapter
the log looks better:

![grafik](https://user-images.githubusercontent.com/25422320/118198765-cbd4be80-b451-11eb-8190-385de23db0c6.png)


@arteck 
Do you have a correct time / timezone on your slave?

**Comment by santa81** [comment] 2021-05-14 19:03
Bin mir nicht sicher ob ich einen anderen Fehler habe oder nicht. Wenn es was anderes einfach ignorieren. 

Habe keinen multihost, aber tr64 hat bei mir jetzt auch öfters keine quelle:
![Screenshot_20210514-205548_Chrome Beta.jpg](https://user-images.githubusercontent.com/18234371/118316929-b4501100-b4f7-11eb-8b5a-3cb0ed908ce8.jpg)

Vielleicht liegt es aber auch am tr64.
Alle Versionen sind aktuell beta Status.

**Comment by Feuer-sturm** [comment] 2021-05-14 21:47
The problem is still there on my slave. The time / timezone is still correct.
I just updated to js-controller 3.3.10 and made a restart of iobroker slave

![grafik](https://user-images.githubusercontent.com/25422320/118334853-b2de1300-b50e-11eb-9a0c-10fb39ae41b5.png)

**Comment by GermanBluefox** [comment] 2021-05-17 14:07
As i cannot reproduce it, I ask for assistance: Is the error persists if new messages arrive or is it just by the first read of logs?

**Comment by Feuer-sturm** [comment] 2021-05-18 10:00
Admin 5.0.26
js-controller 3.3.10

@GermanBluefox 
Perhaps this helps.
If the log window is open the problem is not there. If you refresh the page or enter the log menu the first time then the problem is there.

![Animation6-min](https://user-images.githubusercontent.com/25422320/118632265-86f1b480-b7d0-11eb-9df1-5d9d80346096.gif)


![grafik](https://user-images.githubusercontent.com/25422320/118629775-35482a80-b7ce-11eb-98db-e7bf627fe10d.png)

**Comment by GermanBluefox** [comment] 2021-05-18 16:07
Thank you. That helps. Fixed in 5.0.28

**Closed** 2021-05-19 05:04 UTC
Labels: Admin5, bug, fixed
