### ISSUE TITLE
[bug]: Error in GUI!

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#2640] opened 2024-08-30 18:08 UTC
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

```
console.ts:40 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Be.<anonymous> (index.tsx:225:49)
    at Wa (react-dom.production.min.js:156:189)
    at ki (react-dom.production.min.js:260:422)
    at bi (react-dom.production.min.js:259:446)
    at bi (react-dom.production.min.js:259:343)
    at yi (react-dom.production.min.js:258:431)
    at react-dom.production.min.js:282:96
    at ws (react-dom.production.min.js:280:398)
    at ls (react-dom.production.min.js:269:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```

### To Reproduce

n/a

### Expected behavior

no error

### Screenshots & Logfiles

n/a

### Adapter version

admin v7.0.23

### js-controller version

js-controller v6.0.9

### Node version

v20.17.0

### Operating system

docker (official image - v10.0.0)

### Additional context

n/a

**Comment by GermanBluefox** [comment] 2024-09-06 14:54
It is almost imposible to find an error with this bug report. Do you have more information? E.g. what have you done?

**Comment by foxriver76** [comment] 2024-09-23 12:13
Closing as we cannot reproduce this.

**Closed** 2024-09-23 12:13 UTC
Labels: bug
