### ISSUE TITLE
faulty graphical Headline in 5.1.19

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#1060] opened 2021-08-02 16:56 UTC
![admin_issue_5_1_19](https://user-images.githubusercontent.com/11257222/127897089-69998902-6ad9-4d8f-9ca0-41428c54a5f8.png)
The Line with the icons to administrate the page is partially hidden

**Comment by GermanBluefox** [comment] 2021-08-04 15:56
Cannot reproduce

**Comment by Feuer-sturm** [comment] 2022-02-26 22:54
@Homoran Is this issue still active or can we close it?

**Comment by Feuer-sturm** [comment] 2022-04-12 20:56
No more feedback. Issue closed.

**Closed by Feuer-sturm** 2022-04-12 20:56 UTC
Labels: question
