### ISSUE TITLE
[bug]: iobroker actual admin update fail

### ISSUE THREAD

**Issue by GDI68** [ioBroker/ioBroker.admin#2695] opened 2024-09-21 20:05 UTC
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

after the actual iobroker admin update I get a GUI error:

### To Reproduce

admin is not to open with IP-Adress (xxx.xxx.x.xxx:8081)

### Expected behavior

Open the GUI without error

### Screenshots & Logfiles

App.tsx:1657 Error: timeout
    at Connection.ts:1094:28
    at r (helpers.ts:98:17)

console.ts:40 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Error%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at va (react-dom.production.min.js:135:60)
    at e (react-dom.production.min.js:145:372)
    at ko (react-dom.production.min.js:191:308)
    at xi (react-dom.production.min.js:293:9)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
﻿
![GUI_Error](https://github.com/user-attachments/assets/e4a4a67a-ee35-4154-8d46-829f7f968590)
![GUI_Error](https://github.com/user-attachments/assets/221f17ba-a309-4d89-ac63-78142d640589)

### Adapter version

7.?

### js-controller version

6.0.11

### Node version

18.17.1

### Operating system

raspberry pi 4

**Comment by you-jean** [comment] 2024-09-25 06:58
Hello all,
I have similar issue after updating admin to current version. the correct Admin GUI opens for a short period (ca. 3 seconds) but then it switch to the "Error in Gui" failure.

![pic1](https://github.com/user-attachments/assets/a08dcfbe-5872-40ea-99ed-4235292a8703)
![pic2](https://github.com/user-attachments/assets/53c091be-d6bf-4863-b92d-21e468cb20c8)

**Comment by Apollon77** [comment] 2024-09-25 16:51
And the admin instance is running?

**Comment by you-jean** [comment] 2024-09-25 17:43
Yes. It should I checked it and the admin was shortly started. Admin GUI was displayed (but the starting sequence has taken longer than normaly) and than  it comes to a failure.

**Comment by Feuer-sturm** [comment] 2024-09-29 10:07
@you-jean @GDI68 please check if the issue is fixed with admin 7.1.5

**Comment by you-jean** [comment] 2024-09-29 10:53
Hello. Updates to the last admin relese. Issue does not appear again. Thank you for fast replay and solving the  issue. Super Work!

**Closed** 2024-09-29 11:13 UTC
Labels: bug, fixed
