### ISSUE TITLE
History charts not working when using web adapter with encryption(HTTPS)

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.admin#92] opened 2017-09-12 15:06 UTC
This line appears to force the charts to use HTTP, which fails when using encryption (HTTPS) for the web adapter.
https://github.com/ioBroker/ioBroker.admin/blob/fadf1f4592c375144e45078fe573d58c6a92f899/www/js/adminObjects.js#L1211

Please make the schema match the current adapter settings.

**Comment by silmaril42** [comment] 2017-09-12 18:53
I can confirm this problem - see http://forum.iobroker.net/viewtopic.php?f=17&t=8015 in the German forum.
Would love to see this fixed!

**Comment by Apollon77** [comment] 2017-10-07 19:30
Please retest current version, should be fixed since 2.0.4. Please reopen if still a problem

**Closed by Apollon77** 2017-10-07 19:30 UTC

**Comment by silmaril42** [comment] 2017-10-07 19:49
Works like a charm - thanks for fixing!
