### ISSUE TITLE
Cant use Cert

### ISSUE THREAD

**Issue by CarminKern** [ioBroker/ioBroker.admin#1279] opened 2022-01-14 23:23 UTC
**Describe the bug**  
HTTPS certificates do not work.

**To Reproduce**  
Add RSA PRIVATE KEY 
-----BEGIN RSA PRIVATE KEY----- MIIEowIBAA .... xrAWrXnREB -----END RSA PRIVATE KEY-----
Add the admin instance certificate

**Expected behavior**  
The admin instance no longer starts.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/38145343/149596712-adbe78f3-0928-404e-9bdd-747c1a0f880f.png)
![image](https://user-images.githubusercontent.com/38145343/149596765-8c801194-73bc-484a-8f05-dc5cf5dd0f9b.png)

`2022-01-15 00:09:54.166 - info: host.iobroker "system.adapter.admin.0" enabled
2022-01-15 00:09:54.272 - info: host.iobroker instance system.adapter.admin.0 started with pid 4285
2022-01-15 00:09:57.490 - info: admin.0 (4285) starting. Version 5.2.3 in /opt/iobroker/node_modules/iobroker.admin, node: v12.22.9, js-controller: 3.3.22
2022-01-15 00:09:57.608 - info: admin.0 (4285) requesting all states
2022-01-15 00:09:57.609 - info: admin.0 (4285) requesting all objects
2022-01-15 00:09:58.367 - info: admin.0 (4285) received all objects
2022-01-15 00:09:58.494 - error: admin.0 (4285) Cannot create web-server: Error: error:0909006C:PEM routines:get_name:no start line
2022-01-15 00:09:58.497 - info: admin.0 (4285) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-01-15 00:09:59.038 - info: admin.0 (4285) terminating https server on port 443
2022-01-15 00:09:59.082 - error: host.iobroker instance system.adapter.admin.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
2022-01-15 00:09:59.083 - info: host.iobroker Do not restart adapter system.adapter.admin.0 because desired by instance`

**Versions:**  
 - Adapter version: v5.2.3
 - JS-Controller version: 3.3.22
 - Node version:  v12.22.9
 - Operating system: Raspbian Lite (Newest)

**Additional context**  
I think this is the main problem "Cannot create web-server: Error: error:0909006C:PEM routines:get_name:no start line"

Only the Private Key not work, the cert works

**Comment by Apollon77** [comment] 2022-01-14 23:37
duplicate of https://github.com/ioBroker/ioBroker.admin/issues/1212 ?

**Comment by CarminKern** [comment] 2022-01-14 23:41
It's the same problem... How i fix it ?

**Comment by CarminKern** [comment] 2022-01-15 00:12
The solution that was in the other issue unfortunately did not work for me either

**Comment by CarminKern** [comment] 2022-01-15 03:28
After I reinstalled the whole system, I found that the problem was partly due to the NODEJS version.
Now the current version has been installed and iobroker has also been reinstalled. Unfortunately, the certificates and keys used by hand still do not work. However, the keys that were saved locally now work.

**Comment by Apollon77** [comment] 2022-01-16 00:24
But if same issue I close here as duplicate

**Closed by Apollon77** 2022-01-16 00:24 UTC
