### ISSUE TITLE
Cannot edit storage for entities containing + character

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.admin#617] opened 2020-09-02 19:23 UTC
**Describe the bug**  
I create a scene named `Kitchen_Lights_Downlight_+_Dining` using the Scenes plugin. I cannot set InfluxDB/Lovelace/History settings for it (i.e. stuff that reachable via the wrench button in the Objects browser).

**To Reproduce**  
1. Create an entity containing a `+` character
   
   ![image](https://user-images.githubusercontent.com/16245/92026779-cb801180-ed61-11ea-8f09-cef107622d27.png)

1. Click on the wrench icon
1. Instead of opening the storage UI for the entity, an empty storage UI is shown.
   
   ![image](https://user-images.githubusercontent.com/16245/92026830-e81c4980-ed61-11ea-8ac9-05ca12af0a50.png)

In the above case the URL shown in the browser is:

```
https://<iobroker root URL>/#tab-objects/customs/scene.0.Kitchen_Lights_Downlight_%2B_Dining
```

When I change it to:

```
https://<iobroker root URL>/#tab-objects/customs/scene.0.Kitchen_Lights_Downlight_+_Dining
```

The usual UI shows up. Note the unencoded `+` character.

**Expected behavior**  
The usual UI should open.

**Versions:**  
 - Adapter version: 4.1.7
 - JS-Controller version: 3.1.5
 - Node version: v12.18.3
 - Operating system: Raspbian/Docker

**Comment by Apollon77** [comment] 2020-09-02 20:40
duplicate of #615

**Closed** 2020-09-03 06:20 UTC
