### ISSUE TITLE
failed connection to socket.io

### ISSUE THREAD

**Issue by Ralf-Pfalz** [ioBroker/ioBroker.admin#1084] opened 2021-08-10 17:12 UTC
Admin 5.1.23

.. It works, but sometimes..

![socket](https://user-images.githubusercontent.com/84739760/128904354-895154ca-9f28-4ad3-b520-cc3161e6f9b6.JPG)

**Comment by Apollon77** [comment] 2021-08-10 20:47
SSL? duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1070?

**Comment by Ralf-Pfalz** [comment] 2021-08-11 06:10
Nein. Http://

Am Di., 10. Aug. 2021 um 22:47 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by schrorg** [comment] 2021-08-16 06:27
Same problem here, too. No HTTPS.

**Comment by schrorg** [comment] 2021-08-16 06:36
This seems to at least occur on logout:

```
2021-08-16 08:34:36.702  - debug: admin.0 (24202) Unsubscribe STATES: system.host.iot.alive
2021-08-16 08:34:36.703  - debug: admin.0 (24202) Unsubscribe STATES: system.adapter.discovery.0.alive
2021-08-16 08:34:36.703  - debug: admin.0 (24202) Unsubscribe STATES: system.host.*.alive
2021-08-16 08:34:36.703  - debug: admin.0 (24202) Unsubscribe STATES: system.host.*.notifications.*
2021-08-16 08:34:36.703  - debug: admin.0 (24202) Unsubscribe STATES: system.adapter.*.alive
2021-08-16 08:34:36.704  - debug: admin.0 (24202) Unsubscribe STATES: system.adapter.*.connected
2021-08-16 08:34:36.704  - debug: admin.0 (24202) Unsubscribe STATES: system.adapter.*.inputCount
2021-08-16 08:34:36.704  - debug: admin.0 (24202) Unsubscribe STATES: system.adapter.*.memRss
2021-08-16 08:34:36.704  - debug: admin.0 (24202) Unsubscribe STATES: system.adapter.*.outputCount
2021-08-16 08:34:36.704  - debug: admin.0 (24202) Unsubscribe STATES: system.adapter.*.logLevel
2021-08-16 08:34:36.705  - debug: admin.0 (24202) Unsubscribe STATES: system.host.*.diskFree
2021-08-16 08:34:36.705  - debug: admin.0 (24202) Unsubscribe STATES: system.host.*.diskSize
2021-08-16 08:34:36.705  - debug: admin.0 (24202) Unsubscribe STATES: system.host.*.diskWarning
2021-08-16 08:34:36.705  - debug: admin.0 (24202) Unsubscribe STATES: system.host.*.freemem
2021-08-16 08:34:36.705  - debug: admin.0 (24202) Unsubscribe STATES: *.info.connection
2021-08-16 08:34:36.705  - debug: admin.0 (24202) Unsubscribe STATES: admin.0.info.newsFeed
2021-08-16 08:34:36.706  - debug: admin.0 (24202) Unsubscribe OBJECTS: system.adapter.*
2021-08-16 08:34:36.706  - debug: admin.0 (24202) Unsubscribe OBJECTS: system.repositories
2021-08-16 08:34:36.706  - debug: admin.0 (24202) Unsubscribe OBJECTS: system.host.*
2021-08-16 08:34:36.706  - debug: admin.0 (24202) Unsubscribe LOGS: dummy
2021-08-16 08:34:36.706  - debug: admin.0 (24202) Disable logging, because no one socket connected
2021-08-16 08:34:37.109  - error: admin.0 (24202) error
```

**Comment by klein0r** [comment] 2022-02-28 10:32
Duplicate of #1000

**Closed** 2022-06-09 20:17 UTC
Labels: bug
