### ISSUE TITLE
missing explanation for "EDIT" function at HOSTS Tab

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#229] opened 2018-03-28 15:21 UTC
can somebody please add a detailed discription what can be edited here:

Also nothing is shown with "mouse over"

![host_edit](https://user-images.githubusercontent.com/33424168/38038847-3f4987ae-32ac-11e8-88b6-1f32c2e449f3.jpg)
![host edit_1](https://user-images.githubusercontent.com/33424168/38038895-5bdab1fe-32ac-11e8-826e-f214657c81f2.jpg)

Maybe put an example picture here.

Thanks

**Comment by GermanBluefox** [comment] 2018-03-28 17:27
What exactly is not clear?
Gui is like a joke, if you must to explain it, it is bad GUI.

ср, 28 мар. 2018 г., 17:21 wendy2702 <notifications@github.com>:

**Comment by wendy2702** [comment] 2018-03-28 17:54
Which color can be changed?
What can be uploaded after click at the "+" Button?
Why "rename" (Umbenennen) ?

**Comment by GermanBluefox** [comment] 2018-03-28 21:50
Color of the host,
Icon can be uploaded
Rename title of host.

2018-03-28 19:54 GMT+02:00 wendy2702 <notifications@github.com>:

**Comment by Apollon77** [comment] 2018-03-28 22:03
I think the real question is where these Things are used? Only in the lust at tab „hosts” or also on other places?

**Comment by GermanBluefox** [comment] 2018-04-08 12:33
It is not a bug. Just a question, so I close it

**Closed by GermanBluefox** 2018-04-08 12:33 UTC

**Comment by wendy2702** [comment] 2018-04-08 13:34
It was not only a question.
