### ISSUE TITLE
Loading time "tab-objects" with > 20.000 objects

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#891] opened 2021-05-17 14:18 UTC
While using the admin I noticed that there was a slight delay when loading the "tab-objects".

It is hardly noticeable on my test system or dev system with only 2.000-2.500 objects.

However, this is noticeable in my productive system with around 22.000 objects.

After looking at it in the console, I noticed that all objects are reloaded into the browser each time the tab is called up.

Would it be possible here that one could somehow make the whole thing available with the cache?

As a pure, very rough idea, all objects should be loaded the first time the tab object is called and only those objects that may have been added should be reloaded when called up again within the session.

As I said, it is only an idea for performance and absolutely no criticism for the admin 5.

Admin 5 is absolutely great and a brilliant piece of work by @GermanBluefox

**Comment by Apollon77** [comment] 2021-05-17 16:28
In fact @GermanBluefox this is kind of the topic we discussed in Telegram.

One idea to speed this up would be to rewquest such "mass stuff" as a HTTP request (ideally with compression and pot ETAGs) to get it transferred more optimized.

This could already give a boost. Such a "diff" thingy could be even optimize that more

**Comment by GermanBluefox** [comment] 2021-05-17 16:38
Please imlement it yourself if you need it

**Comment by simatec** [comment] 2021-05-17 17:46
I would like to support and implement it, unfortunately I have no idea where and how exactly one should approach the topic.

**Comment by simatec** [comment] 2021-05-21 12:02
If I understand the code correctly, then this is where the objects are loaded somehow.

https://github.com/ioBroker/ioBroker.admin/blob/9ab6cf40f0a6bb4f5f5baffa03db48ad1747d65e/src-rx/src/components/Connection.js#L650

What I haven't understood so far is how the "update" boolean works

https://github.com/ioBroker/ioBroker.admin/blob/9ab6cf40f0a6bb4f5f5baffa03db48ad1747d65e/src-rx/src/components/Connection.js#L673

**Comment by GermanBluefox** [comment] 2021-05-21 17:55
The problem is not to avoid double loading of objects, but to keep objects up to date.

**Comment by simatec** [comment] 2021-05-21 18:14
yes, I absolutely understand that and I think that's really good.  
My idea was to go in the direction of timestamps.  So only update the objects that have changed via the timestamp.
Unfortunately, the only thing I don't have is the opportunity to take action

**Comment by Apollon77** [comment] 2021-05-21 21:38
For this to wprk you need to implement a new parameter into "getAllObjects" to give that timestamp to the server side and there you need to filter (veery roughly without checking too deep now)

**Comment by GermanBluefox** [comment] 2021-05-22 06:49
Stop thinking in a wrong direction. 
Better check the latest Version

**Comment by GermanBluefox** [comment] 2021-05-24 18:23
@simatec  Und?

**Comment by simatec** [comment] 2021-05-24 19:12
Also das laden ist jetzt perfekt. 
vielen dank @GermanBluefox und absoluten Respekt für diesen genialen React Adapter. 
Du hast mit einer wahnsinnig großen Energieleistung was richtig geniales und für iobroker zukunftsweisendes gebaut. 

Danke für deinen unermüdlichen Einsatz 

👍🏻👍🏻👍🏻👍🏻👍🏻

**Closed** 2021-05-24 19:23 UTC
Labels: Admin5, enhancement, help wanted
