### ISSUE TITLE
Bug when deleting adapters

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.admin#385] opened 2019-03-09 17:11 UTC
I had wanted to update my production system with going from radar adapter to radar2 adapter.
I installed radar2 adapter and transferred the settings and device list from old radar adapter and it worked well.

I had now a (not enabled) instance of radar and enabled instance of radar2. 

Now I  went to Admin adapters and deleted the radar adapter but what iobroker did was:
- Deleting both instances radar.0 and radar2.0!
- Removing the radar adapter from the node_mudules (and adapter list)

I had to add again an instance of radar2 which now hand all configuration reset to default!

It seems that you use wildcard after adapter name to search for items to be removed. This wildcard should be after the dot after the adapter name!

This bug cost me now additional hours because I need to take a backup, extract adapter config of radar and put it into new radar! All because admin deleted all the configs!

**Comment by Apollon77** [comment] 2019-03-09 17:35
duplicate of https://github.com/ioBroker/ioBroker.js-controller/issues/320 ... currently only in 2.0.0

**Closed by Apollon77** 2019-03-09 17:35 UTC

**Comment by frankjoke** [comment] 2019-03-09 17:49
Do you mean that it is only on js-controller 2.0.0? That's not true, This is my production system running js-controller 1.4.2!

**Comment by Apollon77** [comment] 2019-03-09 17:52
No, the bug is FIXED in 2.0.0 only. One idea could be a backport to 1.5.x line. See Telegram Dev channel
