### ISSUE TITLE
BUG. In expert mode, install a specific version

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#197] opened 2018-02-13 15:19 UTC
![122](https://user-images.githubusercontent.com/11523624/36157166-cbc6caa6-110b-11e8-8943-8a92a6b54a78.gif)

**Comment by vdemidov** [comment] 2018-02-13 16:22
Duplicate of my issue https://github.com/ioBroker/ioBroker.admin/issues/195

**Comment by eumats** [comment] 2018-02-15 21:43
#185

**Comment by GermanBluefox** [comment] 2018-03-01 21:17
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/195

**Closed by GermanBluefox** 2018-03-01 21:17 UTC
