### ISSUE TITLE
After installing the matrix.org adapter 0.0.7 the admin ui throw an error

### ISSUE THREAD

**Issue by tardar** [ioBroker/ioBroker.admin#1624] opened 2022-07-30 06:41 UTC
**Describe the bug**  
After installing the matrix.org adapter 0.0.7 the admin ui throw an error

**To Reproduce**  
1. Go to 'Adapter'
2. Click on 'Install matrix.org adapter instance'
3. The admin UI reloads

**Expected behavior**  
The admin ui reloads and show all the admin stuff in there

**Screenshots & Logfiles**  
Error after install and open console after error occurs:
`TypeError: Cannot read properties of undefined (reading 'value')
    at vn.renderItem (ConfigText.jsx:36:34)
    at vn.render (ConfigGeneric.jsx:514:39)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124`

After refreshing the page with the console opened:
`TypeError: Cannot read properties of undefined (reading 'value')
    at vn.renderItem (ConfigText.jsx:36:34)
    at vn.render (ConfigGeneric.jsx:514:39)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:269
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14`

![2022-07-30_08-43-30](https://user-images.githubusercontent.com/40645000/181878335-d167ff69-7320-4810-a7ca-40181865f46e.jpg)

**Versions:**  
 - Adapter version: matrix.org 0.0.6
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0
 - Operating system: 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

**Comment by Feuer-sturm** [comment] 2022-07-30 08:53
@tardar which admin version do you use?

**Comment by oelison** [comment] 2022-07-31 07:12
https://github.com/oelison/ioBroker.matrix-org/issues/8 is related to this issue.
Between V0.0.6 and V0.0.7 I have removed all react stuff. In this ticket it is not clear, if this is an update or the first installation.

**Comment by tardar** [comment] 2022-07-31 07:35
Hey and a good morning :)
I installed it fresh from the repo and there the 0.0.6 was listed.
After the install and check from console it shows me the 0.0.7 - so i think the 0.0.7 is installed.
The admin version is 6.2.11

It seems that the error has gone - so i think he installed the 0.0.6 and updated automatically ?
I checked this a few minutes ago.

**Comment by Feuer-sturm** [comment] 2022-07-31 11:35
I just made a test with Admin 6.2.11

- Fresh Install of matrix adapter v0.0.7 -> ok. Settings of instance is shown after installation is finished
- Remove matrix adapter
- Install matrix adapter v0.0.6 using command line and adding instance -> ok
- Update matrix adapter v0.0.6 to v0.0.7 and enter matrix instance settings -> ok

@tardar @oelison Is there still an admin issue from your side? Otherwise we can close this issue.

**Comment by oelison** [comment] 2022-07-31 13:44
I was also not able to reproduce this issue. @Feuer-sturm You could close the issue here. I will left my issue one week open. If there is no other getting this issue, I will close my, too. @tardar is also fine so far, but unclear how to get this error.

**Closed** 2022-08-01 07:13 UTC
Labels: bug, question
