### ISSUE TITLE
[bug]: GUI-Error on deleting object

### ISSUE THREAD

**Issue by beandi** [ioBroker/ioBroker.admin#2396] opened 2024-03-04 08:17 UTC
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I wanted to manually delete an object, which isn't available anymore.
The moment i click the 'bin'/Delete button, a "Error in GUI"-screen pops up.
Tried various objects, always the same error.

### To Reproduce

Just try to manually delete an object in the object tree.

### Expected behavior

Deleting the object without an error

### Screenshots & Logfiles

`Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 15
        Rs
        e
        wo
        Ei
        ks
        ys
        vs
        us
        ss
        Hl
        ls
        ls
        rs
        enqueueSetState
        setState
    onObjectDelete Objects.jsx:223
    onClick ObjectBrowser.jsx:4471
    React 16
        Re
        Be
        Ir
        Ir
        Ur
        Qr
        cs
        Le
        Qr
        qn
        $n
        Wr
        Ar
        Hr
        Hr
        createRoot
    e bootstrap.jsx:24
    72484 bootstrap.jsx:117
    Webpack 5
        t
        promise callback*87816
        t
        <anonymous>
        <anonymous>
react-dom.production.min.js:189:29
    React 15
        fo
        callback
        Ua
        wi
        ki
        bi
        Ss
        Ss
        ss
        Hl
        ls
    (Async: VoidFunction)
        ls
        rs
        enqueueSetState
        setState
    onObjectDelete Objects.jsx:223
    onClick ObjectBrowser.jsx:4471
    React 16
        Re
        Be
        Ir
        Ir
        Ur
        Qr
        cs
        Le
        Qr
        qn
        $n
    (Async: EventListener.handleEvent)
        Wr
        Ar
        Hr
        Hr
        createRoot
    e bootstrap.jsx:24
    72484 bootstrap.jsx:117
    Webpack 5
        t
    (Async: promise callback)
        87816
        t
        <anonym>
        <anonym>
`

### Adapter version

6.15.0

### js-controller version

5.0.19

### Node version

18.17.1

### Operating system

Buanet Docker Image 8.1

**Comment by foxriver76** [comment] 2024-03-04 09:41
duplicate of https://github.com/ioBroker/ioBroker.admin/issues/2393

**Closed by foxriver76** 2024-03-04 09:41 UTC
Labels: bug
