### ISSUE TITLE
Cannot get certificates: TypeError: invalid options argument

### ISSUE THREAD

**Issue by Freaky-BoyHP** [ioBroker/ioBroker.admin#626] opened 2020-09-24 06:09 UTC
Since a few days I try to use a Lets Encrypt certificate.
But I only get the message: Cannot get certificates: TypeError: invalid options argument

Here are the logs

> admin.0 | 2020-09-24 07:55:17.248 | error | (19566) Cannot get certificates: TypeError: invalid options argument
admin.0 | 2020-09-24 07:55:12.465 | info | (19566) accountId:
admin.0 | 2020-09-24 07:55:12.448 | info | (19566) checkAsync failed to find certificates
admin.0 | 2020-09-24 07:55:12.431 | info | (19566) gl getting from disk or registering new
admin.0 | 2020-09-24 07:55:12.430 | info | (19566) [object Object]
admin.0 | 2020-09-24 07:55:12.429 | info | (19566) gl.approveDomains called with certs forNONEand options:
admin.0 | 2020-09-24 07:55:12.427 | info | (19566) gl.getCertificates called ***.myfritz.netwith certs for
admin.0 | 2020-09-24 07:55:07.469 | info | (19566) Use link "https://localhost:8081" to configure.
admin.0 | 2020-09-24 07:55:07.468 | info | (19566) https server listening on port 8081
admin.0 | 2020-09-24 07:55:07.466 | info | (19566) LetsEncrypt challenge server is started on 80
admin.0 | 2020-09-24 07:55:07.429 | info | (19566) created middleware
admin.0 | 2020-09-24 07:55:07.174 | info | (19566) received all objects
admin.0 | 2020-09-24 07:55:05.057 | info | (19566) requesting all objects
admin.0 | 2020-09-24 07:55:05.056 | info | (19566) requesting all states
admin.0 | 2020-09-24 07:55:04.990 | info | (19566) starting. Version 4.1.8 in /opt/iobroker/node_modules/iobroker.admin, node: v12.18.4, js-controller: 3.1.6

**Comment by kopierschnitte** [comment] 2020-09-25 08:28
I also noticed that the renewal process doesn't start/finish anymore on existing installations.

**Comment by Apollon77** [comment] 2020-10-01 16:56
Lets encrypt is not working anymore since december 2019 because of changes on their side. duplicate of https://github.com/ioBroker/ioBroker.js-controller/issues/439

**Closed by Apollon77** 2020-10-01 16:56 UTC
