### ISSUE TITLE
[jsonConfig] Elements of type text do not accept spaces during normal input

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1921] opened 2023-04-15 20:13 UTC
jsonConfig element does not accept spaces wehn entering a text

When entering the text "This is a test" into a text element the spaces cannot be entered normally as spaces at the end of the text are immidiatly removed. One must enter "Thisisatest" and insert the spaces later as a workaround.

Text inpout fields should not ttruncate the text during input but only when leaviong the field. Eventually an option to omit any trimming should be availbale too.

admin 6.4.3
js-controller 4.0.24
running inside dev-server on node 16.17.0

Note: demo config is stored at repository mcm1957/ioBroker.jsonconfig-demo

**Comment by klein0r** [comment] 2023-06-22 16:17
Duplicate of #1768

**Comment by foxriver76** [comment] 2023-07-11 06:02
https://github.com/ioBroker/adapter-react-v5/blob/1931f64590e034be01cf2f2ca57228061d14ca77/schemas/jsonConfig.json#L1104 and https://github.com/ioBroker/ioBroker.admin/blob/807d507350d8f23c3496d29947911ea7ef36ec20/src/src/components/JsonConfigComponent/SCHEMA.md?plain=1#L24

Please try to set `trim: false` personally I also find the default value is suboptimal.

**Comment by mcm1957** [comment] 2023-07-11 06:46
I'll give it a try and come back.

BUT even when trimming is enabled and desired it should occure when leaving the field - not during entering the text blocking embedded spaces. trim defined removing leading and trailing spaces and normal users (me included) would not expect that the input is trigged during writing but only when leaving the field or even only when saving the data

**Closed** 2023-08-22 05:36 UTC
Labels: bug, question, fixed, json_config
