### ISSUE TITLE
log doesn't refresh anymore automatically

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#210] opened 2018-03-06 18:03 UTC
if the log is opened it will freeze at that moment. it has to been refreshed manually.
last version working correctly was 3.1.12 (??)

**Comment by Scrounger** [comment] 2018-03-06 18:54
Also the log in javascript adapter doent show anything more since 3.1.12

**Comment by MeisterTR** [comment] 2018-03-07 04:59
the same in 3.2.3. after update from 3.1.12 to 3.2.3 the log in js works, but after reboot the log was empty

**Comment by MeisterTR** [comment] 2018-03-09 06:40
wired: i just update daswetter and now i see the log in my scripts

**Comment by GermanBluefox** [comment] 2018-03-14 22:53
Can someone find the pattern, how can I reproduce that?

**Comment by GermanBluefox** [comment] 2018-04-10 08:50
Fixed in js-controller 1.4.0

**Closed** 2018-04-12 16:14 UTC
Labels: fixed
