### ISSUE TITLE
Wrong behavior options in sql save states..

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.admin#367] opened 2019-01-24 08:48 UTC
![24-01-2019 113527](https://user-images.githubusercontent.com/6728198/51666093-50277d00-1fce-11e9-856a-91ab3dcd01f2.jpg)
![24-01-2019 113544](https://user-images.githubusercontent.com/6728198/51666098-54539a80-1fce-11e9-90a7-498c8f68ce03.jpg)
This option absolutly non warkable in my case..

**Comment by Apollon77** [comment] 2019-01-24 09:05
duplicate of https://github.com/ioBroker/ioBroker.sql/issues/53

**Closed by Apollon77** 2019-01-24 09:05 UTC

**Comment by Apollon77** [comment] 2019-01-25 05:57
One question: is the denounce time of 2mins intended?

**Comment by Apollon77** [comment] 2019-01-25 06:00
Ps: can you try if it works as intended when you disable the „log changes only“ option?
